# Generated by Django 5.0.1 on 2024-02-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmcaadmin', '0004_committeemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='committee_member_images/'),
        ),
    ]
