# Generated by Django 5.0.1 on 2024-03-11 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_ownerdetails_cperson'),
        ('zmcaadmin', '0006_birthdaywish'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Blog',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('image', models.ImageField(upload_to='blog_images/')),
        #         ('title', models.CharField(max_length=100)),
        #         ('subtitle', models.CharField(max_length=200)),
        #         ('description', models.TextField()),
        #         ('date', models.DateField()),
        #         ('timestamp', models.DateTimeField(auto_now_add=True)),
        #         ('author_name', models.CharField(max_length=100)),
        #         ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=20)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='CarouselImage',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('title', models.CharField(max_length=100)),
        #         ('image', models.ImageField(upload_to='carousel_images/')),
        #         ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
        #     ],
        # # ),
        # migrations.CreateModel(
        #     name='EventNotification',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('event_name', models.CharField(max_length=100)),
        #         ('description', models.TextField()),
        #         ('date', models.DateField()),
        #         ('timestamp', models.DateTimeField(auto_now_add=True)),
        #         ('status', models.CharField(max_length=20)),
        #         ('image', models.ImageField(upload_to='images/')),
        #     ],
        # ),/
            ]
