# Generated by Django 5.0.1 on 2024-03-11 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_ownerdetails_cperson'),
        ('zmcaadmin', '0007_blog_carouselimage_eventnotification_galleryitem_and_more'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Blog',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('image', models.ImageField(upload_to='blog_images/')),
        #         ('title', models.CharField(max_length=100)),
        #         ('subtitle', models.CharField(max_length=200)),
        #         ('description', models.TextField()),
        #         ('date', models.DateField()),
        #         ('timestamp', models.DateTimeField(auto_now_add=True)),
        #         ('author_name', models.CharField(max_length=100)),
        #         ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=20)),
        #     ],
        # # ),
        # migrations.CreateModel(
        #     name='CarouselImage',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('title', models.CharField(max_length=100)),
        #         ('image', models.ImageField(upload_to='carousel_images/')),
        #         ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='EventNotification',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('event_name', models.CharField(max_length=100)),
        #         ('description', models.TextField()),
        #         ('date', models.DateField()),
        #         ('timestamp', models.DateTimeField(auto_now_add=True)),
        #         ('status', models.CharField(max_length=20)),
        #         ('image', models.ImageField(upload_to='images/')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='GalleryItem',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('title', models.CharField(max_length=100)),
        #         ('image', models.ImageField(upload_to='images/')),
        #         ('description', models.TextField()),
        #         ('timestamp', models.DateTimeField(auto_now_add=True)),
        #         ('status', models.CharField(max_length=20)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Membership',
        #     fields=[
        #         ('membership_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('from_date', models.DateField()),
        #         ('to_date', models.DateField()),
        #         ('with_family_amount', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('alone_amount', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
        #     ],
        # ),
        # migrations.RemoveField(
        #     model_name='birthdaywish',
        #     name='recipient',
        # ),
        # migrations.RemoveField(
        #     model_name='birthdaywish',
        #     name='sender',
        # ),
        # migrations.AddField(
        #     model_name='birthdaywish',
        #     name='recipient_email',
        #     field=models.EmailField(default='abc@example.com', max_length=254),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='birthdaywish',
        #     name='sender_email',
        #     field=models.EmailField(default='abc@example.com', max_length=254),
        #     preserve_default=False,
        # ),
        # migrations.CreateModel(
        #     name='MembershipDetail',
        #     fields=[
        #         ('mdid', models.AutoField(primary_key=True, serialize=False)),
        #         ('membership_year', models.CharField(max_length=9)),
        #         ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
        #         ('payment_date', models.DateField()),
        #         ('usercategory', models.CharField(max_length=255)),
        #         ('status', models.IntegerField(choices=[(1, 'Paid'), (0, 'Unpaid')])),
        #         ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zmcaadmin.membership')),
        #         ('user_profile', models.ForeignKey(limit_choices_to={'status': 2}, on_delete=django.db.models.deletion.CASCADE, to='members.userprofile')),
        #     ],
        # ),
    ]
