# Generated by Django 5.2.1 on 2025-08-18 17:14

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name or alias', max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('age', models.PositiveIntegerField()),
                ('address', models.CharField(help_text='Residential or work area', max_length=255)),
                ('service_type', models.CharField(choices=[('Maid', 'Maid'), ('Driver', 'Driver'), ('Security Guard', 'Security Guard'), ('Gardener', 'Gardener'), ('Babysitter', 'Babysitter'), ('Others', 'Others')], max_length=50)),
                ('skills_duties', models.TextField(help_text='Describe skills or duties')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('languages', models.CharField(help_text='Comma-separated list of languages', max_length=255)),
                ('availability', models.CharField(help_text='E.g. Mon–Fri, 8am–5pm', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Suspended', 'Suspended')], default='Submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=255)),
                ('agency_type', multiselectfield.db.fields.MultiSelectField(choices=[('Maids', 'Maids'), ('Drivers', 'Drivers'), ('Security', 'Security'), ('Others', 'Others')], max_length=29)),
                ('owner_contact_person', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('office_address', models.TextField()),
                ('service_categories', multiselectfield.db.fields.MultiSelectField(choices=[('Driver', 'Driver'), ('Maid', 'Maid'), ('Security Guard', 'Security Guard'), ('Garden Boy', 'Garden Boy'), ('Babysitter', 'Babysitter'), ('Others', 'Others')], max_length=55)),
                ('years_in_operation', models.PositiveIntegerField()),
                ('number_of_staff', models.PositiveIntegerField()),
                ('verification_documents', models.FileField(upload_to='verification_docs/')),
                ('preferred_service_area', models.CharField(help_text='Comma-separated regions (e.g. Lusaka, Ndola)', max_length=255)),
                ('availability', models.CharField(help_text='e.g. Mon–Sat, 8am–6pm', max_length=100)),
                ('short_description', models.TextField()),
                ('consent_agreed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Suspended', 'Suspended')], default='Submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
                'ordering': ['-created_at'],
            },
        ),
    ]
