# Generated by Django 5.2.1 on 2025-08-18 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='agency',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='agency', to='services.agency'),
            preserve_default=False,
        ),
    ]
