# Generated by Django 5.2.1 on 2025-08-22 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_post_delete_helperprofile'),
        ('services', '0003_staff_contact_number_staff_email_alter_staff_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Additional info from requester', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_requests', to='services.agency')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_requests', to='members.userprofile')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='services.staff')),
            ],
            options={
                'verbose_name': 'Staff Request',
                'verbose_name_plural': 'Staff Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
