# Generated by Django 5.0.1 on 2024-01-14 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentsDetails',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('owner_first_name', models.CharField(max_length=255)),
                ('owner_last_name', models.CharField(max_length=255)),
                ('contact_no_india', models.CharField(max_length=15)),
                ('contact_no_zm', models.CharField(max_length=15)),
                ('whatsapp_no', models.CharField(max_length=15)),
                ('family_name', models.CharField(max_length=255)),
                ('address_zambia', models.TextField()),
                ('address_india', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('company_name', models.CharField(max_length=255)),
                ('blood_group', models.CharField(max_length=10)),
                ('spouse_name', models.CharField(max_length=255)),
                ('spouse_phone_no', models.CharField(max_length=15)),
                ('spouse_whatsapp_no', models.CharField(max_length=15)),
                ('spouse_email', models.EmailField(max_length=254)),
                ('spouse_dob', models.DateField()),
                ('spouse_work', models.CharField(max_length=255)),
                ('family_photo', models.ImageField(blank=True, null=True, upload_to='family_photos/')),
                ('up', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OtherDetails',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('blood_group', models.CharField(max_length=10)),
                ('relationship_with_owner', models.CharField(max_length=255)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.parentsdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ChildrenDetails',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('child_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('blood_group', models.CharField(max_length=10)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.parentsdetails')),
            ],
        ),
    ]
