# Generated by Django 4.2.4 on 2024-01-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_parentsdetails_otherdetails_childrendetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherdetails',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='otherdetails',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherdetails',
            name='lname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherdetails',
            name='status',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
