# Generated by Django 4.2.4 on 2024-01-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_name_otherdetails_fname_otherdetails_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdetails',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherdetails',
            name='whatsappno',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
