# Generated by Django 5.0.1 on 2024-01-18 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_otherdetails_email_otherdetails_whatsappno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherdetails',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.userprofile'),
        ),
        migrations.RemoveField(
            model_name='childrendetails',
            name='pid',
        ),
        migrations.AddField(
            model_name='childrendetails',
            name='birth_order',
            field=models.IntegerField(choices=[(1, 'Firstborn'), (2, 'Secondborn'), (3, 'Thirdborn'), (4, 'Fourtborn'), (5, 'Fifthborn'), (6, 'Sixthborn'), (7, 'seventhborn'), (8, 'eighthborn'), (9, 'ninenthborn'), (10, 'tenthborn')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childrendetails',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=2, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childrendetails',
            name='status',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childrendetails',
            name='up',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='members.userprofile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OwnerDetails',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('owner_first_name', models.CharField(max_length=255)),
                ('owner_last_name', models.CharField(max_length=255)),
                ('family_name', models.CharField(max_length=255)),
                ('address_zambia', models.TextField()),
                ('lcity', models.CharField(max_length=255)),
                ('lprovince', models.CharField(max_length=255)),
                ('address_india', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('dob', models.DateField()),
                ('blood_group', models.CharField(max_length=10)),
                ('work_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_no_india', models.CharField(max_length=15)),
                ('contact_no_zm', models.CharField(max_length=15)),
                ('whatsapp_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('zmstatus', models.CharField(max_length=15)),
                ('status', models.IntegerField()),
                ('up', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SpouseDetails',
            fields=[
                ('spid', models.AutoField(primary_key=True, serialize=False)),
                ('spouse_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('spouse_dob', models.DateField()),
                ('blood_group', models.CharField(max_length=10)),
                ('spouse_phone_no', models.CharField(max_length=15)),
                ('spouse_whatsapp_no', models.CharField(max_length=15)),
                ('spouse_work', models.CharField(max_length=255)),
                ('spouse_email', models.EmailField(max_length=254)),
                ('status', models.IntegerField()),
                ('up', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='ParentsDetails',
        ),
    ]
