# Generated by Django 5.0.1 on 2024-01-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_otherdetails_pid_remove_childrendetails_pid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherdetails',
            old_name='pid',
            new_name='up',
        ),
    ]
