# Generated by Django 5.0.1 on 2024-01-18 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_rename_pid_otherdetails_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerdetails',
            name='up',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.userprofile'),
        ),
        migrations.AlterField(
            model_name='spousedetails',
            name='up',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.userprofile'),
        ),
    ]
