# Generated by Django 5.0.1 on 2024-01-19 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_ownerdetails_up_alter_spousedetails_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familyphoto',
            fields=[
                ('fpid', models.AutoField(primary_key=True, serialize=False)),
                ('familyphoto', models.ImageField(blank=True, null=True, upload_to='family_photos/')),
                ('status', models.IntegerField()),
                ('up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.userprofile')),
            ],
        ),
    ]
