# Generated by Django 5.0.1 on 2024-01-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_familyphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spousedetails',
            name='status',
            field=models.CharField(choices=[('1', 'LivingInZambia'), ('2', 'LivingInOtherCountry'), ('3', 'Deceased')], max_length=20),
        ),
    ]
