# Generated by Django 5.0.1 on 2024-01-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_spousedetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childrendetails',
            name='birth_order',
            field=models.CharField(choices=[('Firstborn', 'Firstborn'), ('Secondborn', 'Secondborn'), ('Thirdborn', 'Thirdborn'), ('Fourtborn', 'Fourtborn'), ('Fifthborn', 'Fifthborn'), ('Sixthborn', 'Sixthborn'), ('seventhborn', 'seventhborn'), ('eighthborn', 'eighthborn'), ('ninenthborn', 'ninenthborn'), ('tenthborn', 'tenthborn')], max_length=15),
        ),
    ]
