# Generated by Django 5.0.1 on 2024-02-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_aboutus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
