# Generated by Django 5.0.1 on 2024-02-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_delete_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='spousedetails',
            name='spouse_designation',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
