# Generated by Django 4.2.4 on 2024-02-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_spousedetails_spouse_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerdetails',
            name='cperson',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
