# Generated by Django 5.2.1 on 2025-08-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_ownerdetails_cperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('skills', models.CharField(choices=[('Cleaning', 'Cleaning'), ('Cooking', 'Cooking'), ('Childcare', 'Childcare'), ('Elderly care', 'Elderly care')], max_length=50)),
                ('live_in_status', models.CharField(choices=[('LIVE_IN', 'Live-in'), ('LIVE_OUT', 'Live-out')], max_length=10)),
                ('days_hours', models.CharField(help_text='e.g. Mon–Fri, 8am–5pm', max_length=200)),
                ('experience', models.PositiveIntegerField(help_text='Years of experience')),
                ('languages', models.CharField(help_text='e.g. English, Bemba', max_length=200)),
                ('salary_range', models.CharField(blank=True, help_text='Optional', max_length=100)),
                ('availability_date', models.DateField()),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('nrc_document', models.FileField(blank=True, help_text='Upload NRC document (PDF or image)', upload_to='nrc_documents/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
